### ISSUE TITLE
NonNullColumn

### ISSUE THREAD

**Issue by skanderboudawara** [skanderboudawara/sparkcheck#1]
As a developer I want to add a checker to test if Column is Null or Not so that it’s added to the Yaml Checker

```
checks:
  - is_military:
    - non_null:
        is: True
```

if non_null => True then all the Column must not be null
if non_null => False then all the column must be null
