### ISSUE TITLE
NullColumn

### ISSUE THREAD

**Issue by skanderboudawara** [skanderboudawara/sparkcheck#2]
As a developer I want to add a checker to test if Column is Null or Not so that it’s added to the Yaml Checker

```
checks:
  - is_military:
    - is_null:
        is: True
```

if is_null => True then all the Column mus be null
if is_null => False then all the column must not be null
