### ISSUE TITLE
IsInColumn

### ISSUE THREAD

**Issue by skanderboudawara** [skanderboudawara/sparkcheck#3]
As a developer I want to add a checker to test if Column is in a set of array so that it’s added to the Yaml Checker

```
checks:
  - passengers_country:
    - in:
        values: ["USA", "UK", "FR", "DE", "IT", "ES", "JP", "CN", "RU"]
        strategy: "fail"
```

The array can contain, Float, integers, boolean, strings or column names
Also None should be added as a mandatory predicate

Example:
[1, 2, None] will accept if the Column has some null values
[1, 2] Won’t accept if the Column has some null values
