### ISSUE TITLE
RlikeColumn

### ISSUE THREAD

**Issue by skanderboudawara** [skanderboudawara/sparkcheck#4]
As a developer I want to add a checker to test if Column follows a regex patten so that it’s added to the Yaml Checker

```
checks:
  - aircraft_type:
    - pattern:
        value: "Boeing|Airbus"
        strategy: "fail"
        message: "The aircraft type should be an Airbus or a Boeing"
```

The value can be a regexp string or a column_name that already contains regexps

First the string pattern will be checked agains the dataframe columns, if a column exists with the exact name then It will be prioritized
