### ISSUE TITLE
ColumnCompare

### ISSUE THREAD

**Issue by skanderboudawara** [skanderboudawara/sparkcheck#5]
As a developer I want to add a checker to test if Column against another value so that it’s added to the Yaml Checker

```
checks:
  - gate:
    - lower:
        than: 15
        strategy: "fail"
        message: "The gate number should be lower than 15"
```

Accepted comparators:
    "lower": lt,
    "lower_or_equal": le,
    "equal": eq,
    "different": ne,
    "higher": gt,
    "higher_or_equal": ge,

The comparaison can be agains: string, integer, float, boolean or another column
first the value of “than” or “to” will be tested against dataframe columns if the name already exists as a column it will be prioritized
